version: 2.1

# setup: true

# orbs:
#   continuation: circleci/continuation@0.1.2

jobs:
  # setup:
  #   executor: continuation/default
  #   steps:
  #     - checkout
  #     - run:
  #         name: generate config
  #         command: | 
  #           ./generate-config > generated_config.yml
  #     - continuation/continue:
  #         configuration_path: generated_config.yml

  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      - run:
          name: "Pipelines Triggering Pipelines OMG"
          command: |
            curl 'https://internal.circleci.com/private/soc/webhook/8aaa282a-a941-4fe8-a30c-3ff27c9250fb' \
              -X POST \
              -H 'content-type: application/json' \
              -d '{"status": "success"}'

workflows:
  # setup:
  #   jobs:
  #     - setup

 say-hello-workflow:
   jobs:
     - say-hello
      
#  say-hello-tag-workflow:
#    jobs:
#      - say-hello:
#          filters: 
#            tags:
#              only: 
#                - /^v.*/
